[package]
name = "cli"
version = "0.1.0"
authors = ["matsu-chara <matsuy00@gmail.com>"]
edition = "2018"

[dependencies]
api = {path = "../api"}

clap = "2"
reqwest = "0.9.16"
csv = "1.0.7"
serde = "1.0.91"
serde_json = "1.0.39"

[dependencies.chrono]
features = ["serde"]
version = "0.4"
