[package]
name = "bitonic-sorter"
version = "0.1.0"
authors = ["matsu-chara <matsuy00@gmail.com>"]
edition = "2018"

[dependencies]
rand_pcg = "0.1.2"
rand = "0.6.5"
rayon = "1.0.3"
num_cpus = "1.10.0"
