[package]
name = "server"
version = "0.1.0"
authors = ["matsu-chara <matsuy00@gmail.com>"]
edition = "2018"

[dependencies]
api = {path = "../api"}
env_logger = "0.6.1"
log = "0.4.6"
actix-web = "0.7.19"
failure = "0.1.5"
mime = "0.3.13"
