[package]
name = "start-aw"
version = "0.1.0"
authors = ["matsu-chara <matsuy00@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7.19"
serde = "1.0.91"
serde_derive = "1.0.91"
tera = "0.11.20"
